version: '3.9'

services:
  # API Gateway
  api-gateway:
    restart: always
    container_name: api-gateway
    build: ./api_gateway
    depends_on:
      - user-service
      - note-service
    ports:
      - 10000:10000
  # User microservice 
  user-mongodb:
    image: 'mongo:5.0'
    container_name: 'user-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
    volumes:
      - ./user_service/init.js:/docker-entrypoint-initdb.d/init.js:ro
  user-service:
      restart: always
      container_name: user-service
      build: ./user_service
      depends_on:
        - user-mongodb
  # Note microservice
  note-mongodb:
    image: 'mongo:5.0'
    container_name: 'note-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
    volumes:
      - ./note_service/init.js:/docker-entrypoint-initdb.d/init.js:ro
  note-service:
    restart: always
    container_name: note-service
    build: ./note_service
    depends_on:
      - note-mongodb
  