---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10002
mongodb:
  host: note-mongodb
  port: 27017
  username: munselluser
  password: 123qweASD!A
  auth_db: munsell_system
  database: munsell_system
  collection: notes
